name: "Bug Report"
description: Create a report to track bugs.
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: "Describe the bug"
      description: Please enter an explicit description of your issue
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "To reproduce"
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      render: bash
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: If applicable, add screenshots to help explain your problem.
      placeholder: |
        ![DESCRIPTION](LINK.png)
      render: bash
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: bash
    validations:
      required: false
